import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientWrapper from "./components/QueryClientWrapper";
import { AuthContext } from "./components/JWTAuth/AuthContext";

import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <QueryClientWrapper>
      <AuthContext
        authName="_auth"
        authType="cookie"
        cookieDomain={"localhost"}
        cookieSecure={false}
        cookieSameSite={"strict"}
        cookieExpires={10}
        refresh_api_endpoint="http://localhost:5001/session/refresh"
        refreashTokenExpire={"session"}
        verify_api_endpoint="http://localhost:5001/session/verify"
        redirectTo="/"
        API_ENDPOINT="http://localhost:5001"
      >
        {children}
      </AuthContext>
    </QueryClientWrapper>
  );
}
