services:
  next-app:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api-application:
    restart: on-failure
    build: ./backend/src
    ports:
      - "81:5000"
  api-application-2:
    restart: on-failure
    build: ./backend/src
    ports:
      - "82:5000"
  nginx:
    restart: on-failure
    build: ./backend/nginx
    ports:
      - "80:80"
    depends_on:
      - api-application
      - api-application-2