# ON SOME MACHINES THIS DOESNT PLAY NICE WITH PORTS SO YOU SHOULD USE DOCKER COMPOSE IN BACKEND THEN RUN FRONTEND WITH NPM RUN DEV
services:
  next-app:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api-application:
    restart: on-failure
    build: ./backend/src
    ports: 
      - "5001:5001"
  # api-application-2:
  #   restart: on-failure
  #   build: ./backend/src
  # nginx: # not properly configured for development environment works on production (also isnt necessary for development)
  #   restart: on-failure
  #   build: ./backend/nginx
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - api-application
  #     - api-application-2